services:
  - type: web
    name: grue-sustainability-report
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app --timeout 300 --workers 2
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
